[package]
name = "interface_rh"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding_rs = "0.8.35"
rfd = "0.15.4"
iced = {version = "0.13", features = ["tokio"]}
reqwest = { version = "0.12", features = ["json"] }
dotenv = "0.15.0"
